on:
  pull_request:
  push:
    branches: [main, release]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run build --workspace=overtype
      - run: npm run biome
        working-directory: browser-extension
      - run: npm test
        working-directory: browser-extension
      - run: npm run compile
        working-directory: browser-extension